CodeForAfrica/Dominion.AFRICA

- package.json
- public/index.html
- src/Theme.js
- src/components/ChartFactory.js
- src/components/ChartsContainer.js
- src/components/Hero/Hero.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/ProfileHero/index.js
- src/components/Search/SearchResults.js
- src/lib/api.js
- src/pages/Profile.js
- yarn.lock
- Waiting on new rc fixes https://github.com/CodeForAfrica/HURUmap-UI/pull/32 to styles the title and subtitle.
> use release candidate to render charts

- src/components/ChartFactory.js
- src/data/charts.json
> Adding Charts Definitions

- package.json
- yarn.lock
> Fix a couple of peer dependencies.

- src/components/ChartFactory.js
- src/components/Header/Header.js
- src/components/Header/Navigation.js
- src/components/Hero/CountryHero.js
- src/components/Hero/Hero.js
- src/components/Hero/HomeHero.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/ProfileHero/index.js
- src/components/Hero/TitleHero.js
> Fix header

- src/components/Data/DatasetsContent.js
- src/components/Data/DocumentsContents.js
- src/components/Header/Header.js
- src/components/Header/Navigation.js
- src/components/Hero/CountryHero.js
- src/components/Hero/Hero.js
- src/components/Hero/HomeHero.js
- src/components/Hero/HomeHeroMap.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/ProfileHero/index.js
- src/components/Hero/TitleHero.js
- src/components/Showcase/StoryList.js
- src/components/Showcase/index.js
> [Bugs] Remove height vh on hero components

- src/components/ChartFactory.js
Added more charts with aggregration
> more charts with aggregates

- src/components/Hero/CountryHero.js
- src/components/SocialMedia.js
- src/data/charts.json
> [Bugs] Update social media links + others

- package-lock.json
- package.json
- src/components/CountryPartners/index.js
- src/components/ProfileReleases/index.js
- src/pages/Profile.js
> [Bugs] Add Citation section + Removing Snyk

- src/components/CountryPartners/index.js
- src/components/Hero/Hero.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/SocialMedia.js
- src/pages/About.js
- src/pages/Resources.js
> [Bugs] Update changes

- src/components/Showcase/StoryCard.js
- src/components/Showcase/StoryList.js
> Remove Verticle scroll in gridlist

- src/components/About/Info.js
- src/components/ArrowButton.js
- src/components/CountryPartners/index.js
- src/components/Header/Header.js
- src/components/Header/Navigation.js
- src/components/Hero/Hero.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/TitleHero.js
- src/components/Modal/ContactUs.js
- src/components/Modal/PortalChooser.js
- src/components/Modal/index.js
- src/components/ProfileReleases/index.js
- src/components/ProfileTabs.js
- src/components/Search/SearchResults.js
- src/components/Search/index.js
- src/pages/Profile.js
- src/pages/Resources.js
> Fix console warnings 

- src/components/ChartFactory.js
- src/components/ProfileSectionTitle.js
- src/components/ProfileTabs.js
- src/pages/Profile.js
> Charts section rendering taking too long and blocking UI

- public/index.html
- src/pages/Profile.js
Fix font styles to match design
> Fix fonts and style

- src/components/ProfileTabs.js
> Improve Profile Tabs

- src/components/ProfileSectionTitle.js
Update the profile section titles to work with the designs.
Please delete options that are not relevant.
> Update Profile Section Title Design

- src/components/ChartFactory.js
- src/components/ProfileSectionTitle.js
- src/data/charts.json
- src/pages/Profile.js
> Chart source definition

- README.md
- package.json
- scripts/chartsDefinitionsApplyUniqueId.js
- src/App.js
- src/components/ChartFactory.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/ProfileHero/index.js
- src/data/charts.json
- src/data/queries.js
- src/data/useChartDefinitions.js
- src/data/useProfileLoader.js
- src/pages/Embed.js
- src/pages/Profile.js
- yarn.lock
```
<iframe src="http://localhost:3000/embed/level1-ZA_1_003/sectionIm8gSDP8/chartErJC8igE />
```
> Embed Page

- src/App.js
- src/components/ProfileSectionTitle.js
- src/pages/Profile.js
Use config supported countries to create the url params.
> Use config supported countries

- package.json
- src/Theme.js
- src/components/ChartFactory.js
- src/config.js
- src/data/charts.json
- src/pages/Profile.js
- yarn.lock
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Improve Use of Theme

- src/components/Footer/About.js
- src/components/Hero/CountryHero.js
- src/components/Hero/HomeHero.js
- src/components/ProfileReleases/index.js
- src/components/Showcase/index.js
> Content fixes

- src/config.js
- src/data/charts.json
Use consistent possessive apostrophe.
> Fix consistent possessive apostrophe

- src/config.js
> [Hotfix] Fix iframe showcase story link

- src/components/Header/Navigation.js
- src/pages/Profile.js
Regarding title ☝️ 
Fixed above ☝️
> Fix logo country name wrapping

- src/components/ChartFactory.js
- src/data/charts.json
- src/utils/aggregateData.js
Show percent for charts claiming percent data
> Show percent for charts claiming percent data

- src/components/Hero/ProfileHero/Profile.js
> Fix alignment `geoLevel In countryName`

- src/components/ChartFactory.js
- src/components/Hero/Hero.js
- src/components/Hero/ProfileHero/Profile.js
- src/components/Hero/ProfileHero/index.js
- src/components/ProfileSectionTitle.js
- src/data/useProfileLoader.js
- src/lib/api.js
- src/pages/Profile.js
> Fix many warnings and errors

- src/components/ChartFactory.js
> Format NumbersVisual numbers & Fix rounding

- src/components/Modal/GetLocation.js
- src/components/Modal/PortalChooser.js
- src/config.js
- src/lib/api.js
> Fix detect current user location + or browse list point to list on right.

- src/pages/Embed.js
Fix embed page title + subtitle fonts.
> Fix embed page fonts

- src/App.js
- src/index.js
- src/lib/api.js
Redirect errors to error page.
> Redirect errors to error page

- .bumpversion.cfg
- package.json
Use yarn version for versioning releases
N/A
> [Hotfix] Use yarn version for versioning releases

- src/components/Footer/Community.js
- src/components/Footer/Project.js
- src/components/Footer/SocialMedia.js
- src/components/Footer/index.js
The Container component provides the padding needed for an improved UX on small and large devices.
Please delete options that are not relevant.
> Simplify footer structure and use Container

- src/components/CountryPartners/index.js
Fix dominion country partner urls:
N/A
> [Fix] Update country partners urls

- next.config.js
- package.json
- src/components/ErrorContent.js
- src/components/Hero/CountryHero.js
- src/components/Hero/TitleHero.js
- src/components/ServerErrorPage.js
- src/components/Showcase/StoryCard.js
- src/components/Showcase/StoryList.js
- src/components/Showcase/index.js
- src/config.js
- src/lib/api.js
- src/pages/[countrySlug].js
- src/pages/index.js
- yarn.lock
To make it easy for non-technical teams to update showcase stories, we should pull them from Google Sheets.
> Pull showcase stories from Google Sheet

- src/data/charts.json
> [HotFix] Chart source links update

- src/components/Footer/About.js
- src/config.js
- src/data/charts.json
- src/data/sources.sql
We are hiding kenya country profile as there is no land data for now
> Hide Kenya profile

- src/components/FeaturedData/index.js
- yarn.lock
Switch to using HURUmap UI's ChartContainer in **Featured Data**
> [Hotfix] Featured data chart container

- src/config.js
- src/lib/withApollo.js
- src/pages/embed/[geoId]/[sectionId]/[chartId].js
- src/pages/profiles/[geoId].js
Due to CORS issue we have update graphql url to  `graphql.dominion.africa`
> Update graphql url

- src/config.js
Reverts CodeForAfrica/Dominion.AFRICA#69
> Revert "Update graphql url"

- .dockerignore
- .github/workflows/main.yml
- Dockerfile
- contrib/dokku/Dockerfile
- package.json
Adds Dokku docker image deployment
> Adds Dokku docker image deployment 

- .github/workflows/main.yml
- Dockerfile
> Fix docker build
